nix: ugprade nixpkgs to match version use in mobile
To match the version we upgrade to in:
https://github.com/status-im/status-mobile/pull/14944

I'm upgrading Protobuf to `3.20` since `3.17` is gone:
```
error: protobuf3_17 does not receive updates anymore and has been removed
```
Not sure if that's a big deal.

Signed-off-by: Jakub Sokołowski <jakub@status.im>