fix(nix): backport Android SDK error fixes
Resolves this error caused by Zerokit:
error: aarch64-darwin not supported for Android SDK. Use: NIXPKGS_SYSTEM_OVERRIDE=x86_64-darwin

Backports changes from this PR:
https://github.com/logos-messaging/logos-messaging-nim/pull/3694

Signed-off-by: Jakub Sokołowski <jakub@status.im>